SET GLOBAL log_bin_trust_function_creators = 1;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_BIENBANNHAN`(IDKHO INT, PHILIENTINH INT, NGAYNHAN DATE, PHINOITHANH INT, IDNGUOIGUI INT, IDNGUOINHAN INT)
BEGIN
	CALL INSERT_BIENBANNGUOIDUNG(IDKHO);
	INSERT INTO `ass2`.`BienBanNhan`
	(`ID`,
	`PhiLienTinh`,
	`NgayNhan`,
	`PhiNoiThanh`,
	`IDNguoiGui`,
	`IDNGuoiNhan`)
	VALUES
	((SELECT LAST_INSERT_ID()),
    PHILIENTINH,
	NGAYNHAN,
	PHINOITHANH,
	IDNGUOIGUI,
	IDNGUOINHAN);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_KIENHANG`(KHOILUONG INT, IDBIENBANNGUOIDUNG INT, IDBIENBANNHAPXUAT INT)
BEGIN
	IF KHOILUONG <= 0 THEN
	SIGNAL SQLSTATE '45000'
		SET MESSAGE_TEXT = 'KHOI LUONG PHAI LON HON 0';
	END IF;

	INSERT INTO `ass2`.`KienHang`
	(`KhoiLuong`,
	`IDBienBanNguoIDung`,
	`IDBienBanNhapXuat`)
	VALUES
	(KHOILUONG, IDBIENBANNGUOIDUNG, IDBIENBANNHAPXUAT);

END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_BIENBANXUAT`(KHOID INT, NHANVIENIO VARCHAR(15), CUOCXEID INT, KHODICHID INT)
BEGIN
	CALL INSERT_BIENBANNHAPXUAT(KHOID, NHANVIENIO, CUOCXEID);
    INSERT INTO `ass2`.`BienBanXuat`
	(`ID`,
	`KhoDichID`)
	VALUES
	((SELECT last_insert_id()),
	KHODICHID);

END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_CUOCXENOITHANH`(NGAYDEN DATE, NGAYDI DATE, PHUONGTIEN VARCHAR(20), TAIXECMND VARCHAR(15), LOXECMND VARCHAR(15))
BEGIN
	CALL INSERT_CUOCXE(NGAYDEN, NGAYDI, PHUONGTIEN, TAIXECMND, LOXECMND);

	INSERT INTO `ass2`.`CuocXeNoiThanh`
	(`ID`)	VALUES
	((SELECT LAST_INSERT_ID()));
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_CUOCXELIENTINH`(NGAYDEN DATE, NGAYDI DATE, PHUONGTIEN VARCHAR(20), TAIXECMND VARCHAR(15), LOXECMND VARCHAR(15))
BEGIN
	CALL INSERT_CUOCXE(NGAYDEN, NGAYDI, PHUONGTIEN, TAIXECMND, LOXECMND);

	INSERT INTO `ass2`.`CuocXeLienTinh`
	(`ID`)	VALUES
	((SELECT LAST_INSERT_ID()));
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UPDATE_NHANVIEN`(OLDCMND VARCHAR(15), NEWCMND VARCHAR(15), NGAYTUYENDUNG DATE, DIACHI CHAR(255), HO CHAR(255), TEN CHAR(255))
BEGIN
	UPDATE NhanVien 
    SET CMND = NEWCMND, NgayTuyendung = NGAYTUYENDUNG, DiaChi = DIACHI, Ho = HO, Ten = TEN
    where CMND = OLDCMND;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_CUOCXE`(NGAYDEN DATE, NGAYDI DATE, PHUONGTIEN VARCHAR(20), TAIXECMND VARCHAR(15), LOXECMND VARCHAR(15))
BEGIN
	IF datediff(NGAYDEN, NGAYDI) < 0 THEN
		SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'NGAYDEN HOAC NGAYDI KHONG HOP LE';
	END IF;
	INSERT INTO `ass2`.`CuocXe`
	(
	`NgayDen`,
	`NgayDi`,
	`PhuongTien`,
	`TaiXeCMND`,
	`LoXeCMND`)
	VALUES
	(NGAYDEN, NGAYDI, PHUONGTIEN, TAIXECMND, LOXECMND);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UPDATE_KHO`(IDKHO INT, TINH VARCHAR(50), DIACHI VARCHAR(50), DIENTICH FLOAT, TEN VARCHAR(50))
BEGIN
	IF DIENTICH < 0 THEN
		SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'DIENTICH PHAI LA MOT SO DUONG';
	END IF;
    
    UPDATE Kho
    SET Tinh = TINH, DiaChi = DIACHI, DienTich = DIENTICH, Ten = TEN
    WHERE ID = IDKHO;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_LoXe`(CMND VARCHAR(15), NGAYTUYENDUNG DATE, DIACHI CHAR(255), HO CHAR(255), TEN CHAR(255))
BEGIN
	CALL INSERT_NHANVIEN(CMND, NGAYTUYENDUNG, DIACHI, HO, TEN);
    INSERT INTO LoXe (CMND)
    valueS(CMND);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_GAN`(YEUCAUID INT, CUOCXEID INT, PHANHOI ENUM('Cho', 'TuChoi', 'ChapNhan'))
BEGIN
	INSERT INTO `ass2`.`Gan`
	(`YeuCauID`,
	`CuocXeID`,
	`PhanHoi`)
	VALUES
	(YEUCAUID, CUOCXEID, PHANHOI);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UPDATE_KHACHHANG`(CID INT, TEN CHAR(30), DIACHI VARCHAR(50))
BEGIN
	UPDATE KhachHang
    set TEN = TEN, DIACHI = DIACHI
    WHERE ID = CID;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_BIENBANNGUOIDUNG`(IDKHO INT)
BEGIN
	INSERT INTO `ass2`.`BienBanNguoiDung`
	(`IDKho`)
	VALUES
	(IDKHO);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_BIENBANNHAP`(KHOID INT, NHANVIENIO VARCHAR(15), CUOCXEID INT, KHONGUONID INT)
BEGIN
	CALL INSERT_BIENBANNHAPXUAT(KHOID, NHANVIENIO, CUOCXEID);
	INSERT INTO `ass2`.`BienBanNhap`
	(`ID`,`KhoNguonID`)
	VALUES
	((SELECT last_insert_id()), KHONGUONID);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_KHO`(TINH VARCHAR(50), DIACHI VARCHAR(50), DIENTICH FLOAT, TEN VARCHAR(50))
BEGIN
	IF DIENTICH < 0 THEN
		SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'DIENTICH PHAI LA MOT SO DUONG';
	END IF;
    
    INSERT INTO `ass2`.`Kho`
	(`Tinh`,
	`DiaChi`,
	`DienTich`,
	`Ten`)
	VALUES
	(TINH, DIACHI, DIENTICH, TEN);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_KHACHHANG`(TEN CHAR(30), DIACHI VARCHAR(50))
BEGIN
	INSERT INTO KhachHang (Ten, DiaChi)
    VALUES (TEN, DIACHI);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_BIENBANGUI`(IDKHO INT, PHINOITHANH INT, NGAYGUI DATE, IDNGUOIGUI INT, IDNGUOINHAN INT)
BEGIN
	CALL INSERT_BIENBANNGUOIDUNG(IDKHO);
	INSERT INTO `ass2`.`BienBanGui`
	(`ID`,
    `PhiNoiThanh`,
	`NgayGui`,
	`IDNguoiGui`,
	`IDNGuoiNhan`)
	VALUES
	((SELECT LAST_INSERT_ID()),
    PHINOITHANH,
	NGAYGUI,
	IDNGUOIGUI,
	IDNGUOINHAN);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_NGUOINHAN`(TEN CHAR(30), DIACHI VARCHAR(50))
BEGIN
	CALL INSERT_KHACHHANG(TEN, DIACHI);
    
	INSERT INTO `ass2`.`NguoiNhan`
	(`ID`)
	VALUES
	((SELECT last_insert_id()));

END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` FUNCTION `LoinhuanTrongNam`(YR YEAR) RETURNS int(11)
BEGIN
	SET @Noithanh_GUI = 0;
    SET @Noithanh_NHAN = 0;
    SET @Lientinh_GUI = 0;
    select SUM(PhiNoiThanh) into @Noithanh_GUI from BienBanGui where (select year(NgayGui) from BienBanGui) = YR;
    select SUM(PhiNoiThanh) into @Noithanh_NHAN from BienBanNhan where (select year(NgayNhan) from BienBanNhan) = YR;
    select SUM(PhiLienTinh) into @Lientinh_GUI from BienBanGui where (select year(NgayGui) from BienBanGui) = YR;
    
	RETURN @Noithanh_GUI + @Noithanh_NHAN + @Lientinh_GUI;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` FUNCTION `TongChiTieuCuaKhachHang`(id int) RETURNS int(11)
BEGIN
        set @gui = 0;
        select Sum(PhiNoithanh) into @gui from BienBanGui
        where IDNguoiGui = id;
        
        set @nhan = 0;
        select (Sum(PhiLientinh) + Sum(PhiNoithanh)) into @nhan from BienBanNhan
        where IDNguoiNhan = id;
RETURN @gui + @nhan;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UPDATE_BIENBANNGUOIDUNG`(CID INT, NIDKHO INT)
BEGIN
	UPDATE BienBanNguoiDung
    SET IDKHO = NIDKHO
    WHERE ID = CID;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `KhachHangDenTu`(diachi1 varchar(10))
BEGIN
	select * from KhachHang
    where instr(DiaChi, diachi1) <> 0;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `TopNKhachHangGui`(n int)
BEGIN
	select count(*) as SoLanGui, ID, Ho, Ten from BienBanGui join KhachHang
    where ID = IDNguoiGui
    group by ID
    order by SoLanGui
    limit n;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_YEUCAULAYHANG`(SOKIENHANG INT, KHOILUONG INT, IDBIENBANGUI INT)
BEGIN
	IF KHOILUONG <= 0 THEN
		SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'KHOI LUONG PHAI LON HON 0';
	ELSEIF SOKIENHANG <= 0 THEN
		SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'SO KIEN HANG PHAI LON HON 0';
	else
		INSERT INTO YeuCauLayHang (SoKienHang, KhoiLuong, IDBienBanGui)
        values (SOKIENHANG, SOLUONG, IDBIENBANGUI);
	end if;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_NHANVIEN`(CMND VARCHAR(15), NGAYTUYENDUNG DATE, DIACHI CHAR(255), HO CHAR(255), TEN CHAR(255))
BEGIN
	INSERT INTO NhanVien (CMND, NgayTuyendung, DiaChi, Ho, Ten)
    VALUES (CMND, NGAYTUYENDUNG, DIACHI, HO, TEN);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_XENOITHANH`(BIENSOXE VARCHAR(20), HANGXE VARCHAR(50), NGAYMUAVE DATE, LOAIXE VARCHAR(20))
BEGIN
		CALL INSERT_PHUONGTIEN(BIENSOXE, HANGXE, NGAYMUAVE);
        INSERT INTO XeNoiThanh (BienSoXe, LoaiXe)
        Values (BIENSOXE, LOAIXE);  
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_PHUONGTIEN`(BIENSOXE VARCHAR(20), HANGXE VARCHAR(50), NGAYMUAVE DATE)
BEGIN
	insert INTO PhuongTien(BienSoXe, HangXe, NgayMuaVe)
    values (BIENSOXE, HANGXE, NGAYMUAVE);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_YEUCAU`(YEUCAUID INT, KHACHHANGID INT)
BEGIN
	INSERT INTO YeuCau (YeuCauID, KhachHangID)
    values (YEUCAUID, KHACHHANGID);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_BIENBANNHAPXUAT`(KHOID INT, NHANVIENIO VARCHAR(15), CUOCXEID INT)
BEGIN
	INSERT INTO `ass2`.`BienBanNhapXuat`
	(`KhoID`,
	`NhanVienIO`,
	`CuocXeID`)
	VALUES
	(KHOID,
	NHANVIENIO,
	CUOCXEID);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_SDTKHACHHANG`(SDT CHAR(10), IDKHACHHANG INT)
BEGIN
	IF SUBSTRING(SDT, 1, 1) != '0' THEN
		SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'SO DIEN THOAI KHONG HOP LE';
	ELSE 
		INSERT INTO SdtKhachHang(Sdt, IDKhachHang)
        values (SDT, IDKHACHHANG);
	END IF;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_NGUOIGUI`(TEN CHAR(30), DIACHI VARCHAR(50))
BEGIN
	CALL INSERT_KHACHHANG(TEN, DIACHI);
    
	INSERT INTO `ass2`.`NguoiGui`
	(`ID`)
	VALUES
	((SELECT last_insert_id()));

END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_TAIXE`(CMND VARCHAR(15), NGAYTUYENDUNG DATE, DIACHI CHAR(255), HO CHAR(255), TEN CHAR(255))
BEGIN
	CALL INSERT_NHANVIEN(CMND, NGAYTUYENDUNG, DIACHI, HO, TEN);
    INSERT INTO TaiXe (CMND)
    valueS(CMND);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_NHANVIENNHAPXUAT`(CMND VARCHAR(15), NGAYTUYENDUNG DATE, DIACHI CHAR(255), HO CHAR(255), TEN CHAR(255))
BEGIN
	CALL INSERT_NHANVIEN(CMND, NGAYTUYENDUNG, DIACHI, HO, TEN);
    INSERT INTO NhanVienNhapXuat (CMND)
    valueS(CMND);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_NGUOIQUANLY`(CMND VARCHAR(15), NGAYTUYENDUNG DATE, DIACHI CHAR(255), HO CHAR(255), TEN CHAR(255))
BEGIN
	CALL INSERT_NHANVIEN(CMND, NGAYTUYENDUNG, DIACHI, HO, TEN);
    INSERT INTO NguoiQuanLy (CMND)
    valueS(CMND);
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_XELIENTINH`(BIENSOXE VARCHAR(20), HANGXE VARCHAR(50), NGAYMUAVE DATE, SOCONTAINER INT)
BEGIN
	IF SOCONTAINER < 0 THEN
		SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'SO CONTAINER PHAI LA SO DUONG';
	ELSE
		CALL INSERT_PHUONGTIEN(BIENSOXE, HANGXE, NGAYMUAVE);
        INSERT INTO XeLienTinh (BienSoXe, SoContainer)
        Values (BIENSOXE, SOCONTAINTER);
	END IF;    
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_SDTNHANVIEN`(SDT CHAR(10), CMNDNHANVIEN INT)
BEGIN
	IF SUBSTRING(SDT, 1, 1) != '0' THEN
		SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'SO DIEN THOAI KHONG HOP LE';
	ELSE 
		INSERT INTO SdtNhanVien (Sdt, CMNDNhanVien)
        values (SDT, CMNDNHANVIEN);
	END IF;
END$$
DELIMITER ;
